### ISSUE TITLE
Files kb_act.lst, kb_def.lst, and kb_keys.lst conflict with HL1 valve data

### ISSUE THREAD

**Issue by glebm** [FWGS/xash-extras#3]
The files kb_act.lst, kb_def.lst, and kb_keys.lst are also present in the current steam version of HL1

Are the files provided here "better"?

**Comment by nekonomicon** [comment]
What about WON?

**Comment by a1batross** [comment]
They are not better, they are provided just for compatibility.

However, they are maybe kinda useless right now because:
1) They actually came from original Xash3D extras archive which meant to be unpacked over Half-Life game files (i.e. replace) but we pack extras into *.pak archive (i.e. providing a fallback)
2) They probably added because Xash3D's original menu didn't supported Steam translations files but I have implemented that in mainui_cpp.

**Comment by glebm** [comment]
Shall we remove these files then?

> we pack extras into *.pak archive

Where is this pak archive?

**Comment by glebm** [comment]
Found it in https://github.com/FWGS/xash-extras/releases/latest/download/extras.pak
